/*
 * Reference:
 * http://www.bankrate.com/calculators/mortgages/amortization-calculator.aspx?loanAmount=165000&years=30&terms=360&interestRate=4.50&loanStartDate=15+Oct+2017&email=&lightbox=true&show=false&showRt=true&prods=216&monthlyAdditionalAmount=0&yearlyAdditionalAmount=0&yearlyPaymentMonth=+Oct+&oneTimeAdditionalPayment=0&oneTimeAdditionalPaymentInMY=+Nov+2017&ic_id=mtg_amort_calc_calculate_btn
 */
package com.extant.utilities;
import java.lang.Math;

/**
 *
 * @author jms
 */
public class Amortization 
    extends javax.swing.JDialog
{
    /**
     * Creates new form Amortization
     */
    public Amortization(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.setLocation(800, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrincipal = new javax.swing.JTextField();
        txtIntRate = new javax.swing.JTextField();
        txtNPeriods = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        btnCalcPayment = new javax.swing.JButton();
        btnMakeSchedule = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtFundingDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Principal"));

        txtIntRate.setBorder(javax.swing.BorderFactory.createTitledBorder("Annual Interest Rate"));

        txtNPeriods.setBorder(javax.swing.BorderFactory.createTitledBorder("No. of Months"));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Amortization Calculator");

        lblPayment.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPayment.setText("The monthly payment is ....");

        btnCalcPayment.setText("Compute Monthly Payment");
        btnCalcPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcPaymentActionPerformed(evt);
            }
        });

        btnMakeSchedule.setText("Compute Amortization Schedule");
        btnMakeSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeScheduleActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtFundingDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Funding Date"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCalcPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIntRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtFundingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMakeSchedule)
                        .addGap(154, 154, 154))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIntRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFundingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMakeSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcPaymentActionPerformed
        setup();
        lblPayment.setText("The monthly payment is:  " + Strings.formatPennies(calcPayment()/100));
    }//GEN-LAST:event_btnCalcPaymentActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMakeScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeScheduleActionPerformed
        makeSchedule();
    }//GEN-LAST:event_btnMakeScheduleActionPerformed

    public void setup()
    {
        double annualRate = Double.parseDouble(txtIntRate.getText());
        r = annualRate / 1200.0;
        principal = Double.parseDouble(txtPrincipal.getText());
        nMonths = Double.parseDouble(txtNPeriods.getText());
        //System.out.println("setup: " + annualRate +"  " + principal +"  "+ nMonths);
    }

    public long calcPayment()
    {
        double t = java.lang.Math.pow(1+r, nMonths);
        double num = r * t;
        double den = t - 1;
        long paymentPennies = double2Pennies((principal * 100.0 * num) / den);
        return paymentPennies;
    }

    public void makeSchedule()
    {
        payLine = new StringBuffer();
        payLine.append("Title Page\\n");
        fundingDate = new Julian(txtFundingDate.getText());
        payDate = nextDate(fundingDate);
        payoffPennies = double2Pennies(principal);
        long interestPennies;
        for (int i=0; i<nMonths; ++i)
        {
            payLine.append(payDate.toString("mm-dd-yyyy"));
            interestPennies = double2Pennies(payoffPennies * r);  //interest portion of this payment
            payoffPennies -= (paymentPennies - interestPennies);  //principal remaining after this payment
            payLine.append( payDate.toString("mm-dd-yyyy") + " int="+interestPennies+"  prin="+(paymentPennies-interestPennies)+ "  payoff="+payoffPennies);
            Console.println(payLine.toString());  payLine =(new StringBuffer());
            payDate = nextDate(payDate);
        }
        System.out.print(payLine);
    }

    public Julian nextDate(Julian currentDate)
    {
        Julian saveCurrentDate = currentDate;
        Julian nextMonth = currentDate.addMonths(1);
        if (nextMonth.getYear() != saveCurrentDate.getYear())
        {
            doAnnualTotals(saveCurrentDate);
            
        }
        //currentDate = nextMonth;
        return nextMonth;
    }
    
    public void doAnnualTotals(Julian date)
    {
        Console.println(date.toString("mm-dd-yyyy") + "annual totals ...");
    }

    public long double2Pennies(double x)
    {
        return (long)java.lang.Math.round(100.0 * x);
    }

    double r;            // Interest rate per period
    double principal;    // Begining principal amount
    double nMonths;      // Number of months full term
    Julian payDate;
    long paymentPennies;
    Julian fundingDate;
    long payoffPennies;       // Amount to payoff
    StringBuffer payLine;
    long annualInterest;
    long annualPrincipal;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Amortization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Amortization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Amortization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Amortization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Amortization dialog = new Amortization(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcPayment;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMakeSchedule;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFundingDate;
    private javax.swing.JTextField txtIntRate;
    private javax.swing.JTextField txtNPeriods;
    private javax.swing.JTextField txtPrincipal;
    // End of variables declaration//GEN-END:variables
}
